version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 31115:31115
      - 31116:31116
      - 31116:31116/udp
      - 31118:31118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r rustdesk.example.com:31117
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 31117:31117
      - 31119:31119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
